spring:
  data:
    mongodb:
      host: account-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27017
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service:5000/uaa
      client:
        provider:
          auth-service:
            token-uri: http://auth-service:5000/uaa/oauth2/token
        registration:
          auth-service:
            provider: auth-service
            authorization-grant-type: client_credentials
            client-id: account-service
            client-secret: ${ACCOUNT_SERVICE_PASSWORD}
            scope: server

app:
  oauth2:
    client-registration-id: auth-service

server:
  servlet:
    context-path: /accounts
  port: 6000
