spring:
  data:
    mongodb:
      host: statistics-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27017
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service:5000/uaa

server:
  servlet:
    context-path: /statistics
  port: 7000

rates:
  url: https://api.exchangeratesapi.io
